jvm_binary(
    name = "sbf-app",
    main = "com.twitter.sbf.app.Main",
    dependencies = [
        "src/java/com/twitter/sbf/app",
    ],
)

jvm_binary(
    name = "simclusters-app",
    main = "com.twitter.sbf.simclusters_app.Main",
    dependencies = [
        "src/java/com/twitter/sbf/simclusters_app",
    ],
)

jvm_binary(
    name = "compare-to-pure-random",
    main = "com.twitter.sbf.app.CompareToPureRandom",
    dependencies = [
        "src/java/com/twitter/sbf/app",
    ],
)
